#!/usr/bin/env python

import argparse
import os
import sys

from apply_patches import apply_patches


def main(argv):
  parser = argparse.ArgumentParser(
      description='Apply patches to the current repo')
  parser.add_argument("patch_dir",
      help="directory containing patches to apply")
  parser.add_argument("-3", "--3way",
      action="store_true", dest='threeway',
      help="use 3-way merge to resolve conflicts")
  args = parser.parse_args(argv)

  apply_patches({args.patch_dir: '.'}, threeway=args.threeway)


if __name__ == '__main__':
  main(sys.argv[1:])
